orbs:
  aws-ecr: circleci/aws-ecr@6.12.2 # Use the AWS ECR orb in your config

version: 2.1
jobs:
  lint-test:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup project
          command: |
            make build

      - run:
          name: Lint
          command: |
            make lint

      - run:
          name: Compile to js
          command: |
            make compile

workflows:
  version: 2.1
  lint-test:
    jobs:
      - lint-test:
          filters:
            branches:
              ignore: master
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image: # Use the pre-defined `build-and-push-image` job
          dockerfile: Dockerfile
          path: .
          profile-name: CircleCI
          repo: gspreadsheet-api
          tag: '0.0.2'
          requires:
            - lint-test
          filters:
            branches:
              only: master
      - lint-test
