version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup project
          command: |
            make build

      - run:
          name: Compile to js
          command: |
            make compile
workflows:
  version: 2
  build:
    jobs:
      - build
